### ISSUE TITLE
Request for open link to paper

### ISSUE THREAD

**Issue by veriff-javiervgd** [KaenChan/lightqnet#2]
Hi! nice research and thank you for open sourcing your work. I was wondering if it was possible to get an open link to the LightQNet paper :)

**Comment by KaenChan** [comment]
https://github.com/KaenChan/lightqnet-train/blob/main/SPL_LightQNet.pdf

**Comment by veriff-javiervgd** [comment]
Thank you so much for sharing it. This kind of research really helps humanity to get in the right direction as we move into a more inter-connected, digital world in which our identities must be recognizable and trusted.
